version: 2
jobs:
  accept_library_licenses:
            docker:
              - image: circleci/android:api-25-alpha
            environment:
              JVM_OPTS: -Xmx4G
            steps:
              - checkout
              - run: cp -r licenses/. $ANDROID_HOME/licenses
  running_code_quality_tools:
          docker:
            - image: circleci/android:api-25-alpha
          environment:
            JVM_OPTS: -Xmx4G
          steps:
            - checkout
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
               name: Chmod permissions
               command: sudo chmod +x ./gradlew
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - save_cache:
                paths:
                  - ~/.gradle
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Run code quality tools
                command: ./gradlew ktlintCheck
            - store_artifacts:
                      path: app/build/reports/
                      destination: code_quality_results/
            - run:
                name: Run Saddler to commit to pull request
                command: chmod +x app/code_quality_tools/run-gradle-android.sh
            - run:
                name: Run Saddler to commit to pull request
                command: app/code_quality_tools/run-gradle-android.sh


  running_test:
        docker:
          - image: circleci/android:api-25-alpha
        environment:
          JVM_OPTS: -Xmx4G
        steps:
          - checkout
          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          - run:
             name: Chmod permissions
             command: sudo chmod +x ./gradlew
          - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies
          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          - run:
              name: Run Tests
              command: ./gradlew lint test
          - store_test_results:
                    path: app/build/test-results
  build_release:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
workflows:
  version: 2
  check_code_quality:
    jobs:
      - accept_library_licenses
      - running_code_quality_tools:
          requires:
            - accept_library_licenses
#  test_and_build:
#    jobs:
#      - accept_library_licenses
#      - running_test:
#          requires:
#            - accept_library_licenses
#      - build_release:
#          requires:
#            - running_test
